services:
  frontend:
    build: ./app
    ports: 
      - 3000:3333
    container_name: frontend
  api:
    build: ./api
    ports: 
      - 5000:5555
    container_name: api
  mysql:
    image: mysql
    container_name: mysql
#  nginx:
#    image: nginx
  adminer:
    image: adminer:4.8.1
    container_name: adminer