version: '3'

services:
  frontend:
    restart: always
    build: ./frontend
    ports: 
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app:Z
    command: chown $UID:$GID -R /app/node_modules
    container_name: frontend
  api:
    build: ./api
    restart: always
    ports: 
      - 5555:5000
    volumes:
      - /app/node_modules
      - ./api:/app:Z
    depends_on:
      - mysql
    command: chown $UID:$GID -R /app/node_modules
    container_name: api
  mysql:
    image: mysql
    restart: always
    env_file:
      - ./mysql/.env
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: mysql
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8888:8080
    container_name: adminer
  
volumes:
  mysql_data: