service:
  frontend:
    build: ./app
    ports: 3000:3333
    container_name: frontend
  api:
    build: ./api
    ports: 5000:5555
    container_name: api
  mysql:
    image: mysql
#  nginx:
#    image: nginx
  adminer:
    image: adminer