version: '3'

services:
  frontend:
    restart: always
    build: ./frontend
    ports: 
      - 3333:3000
    depends_on:
      - api
    container_name: frontend
  api:
    build: ./api
    restart: always
    ports: 
      - 5555:5000
    depends_on:
      - mysql
    container_name: api
  mysql:
    image: mysql
    restart: always
    env_file:
      - ./mysql/.env
    container_name: mysql
#  nginx:
#    image: nginx
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8888:8080
    container_name: adminer