services:
  frontend:
    build: ./frontend
    ports: 
      - 3333:3000
    container_name: frontend
  api:
    build: ./api
    ports: 
      - 5555:5000
    container_name: api
  mysql:
    image: mysql
    container_name: mysql
#  nginx:
#    image: nginx
  adminer:
    image: adminer:4.8.1
    container_name: adminer